#!/usr/bin/env bash
# Nightly installer.
#
# One-liner install:
#   curl -fsSL https://raw.githubusercontent.com/ulmentflam/nightly/main/install.sh | bash
#
# Or, if you've already cloned the repo:
#   bash install.sh
#
# Honors these environment variables:
#   NIGHTLY_HOME      where to clone the source tree (default: ~/.local/share/nightly)
#   NIGHTLY_VERSION   branch / tag / commit to check out (default: main)
#   NIGHTLY_BIN       where to drop the `nightly` shim (default: ~/.local/bin)
#   NIGHTLY_REPO      git remote URL (default: https://github.com/ulmentflam/nightly.git)
#
# Re-running this script updates an existing install in place; it never
# clobbers your local .nightly/ or .planning/ folders in repos you've
# initialized.

set -euo pipefail

NIGHTLY_HOME="${NIGHTLY_HOME:-$HOME/.local/share/nightly}"
NIGHTLY_VERSION="${NIGHTLY_VERSION:-main}"
NIGHTLY_BIN="${NIGHTLY_BIN:-$HOME/.local/bin}"
NIGHTLY_REPO="${NIGHTLY_REPO:-https://github.com/ulmentflam/nightly.git}"

# ── color helpers (only when stdout is a TTY) ─────────────────────────────
if [ -t 1 ]; then
    _b=$'\033[1m'
    _g=$'\033[32m'
    _y=$'\033[33m'
    _r=$'\033[31m'
    _d=$'\033[2m'
    _z=$'\033[0m'
else
    _b=''
    _g=''
    _y=''
    _r=''
    _d=''
    _z=''
fi

info() { printf '%s::%s %s\n' "$_d" "$_z" "$*"; }
ok()   { printf '%s✓%s %s\n' "$_g" "$_z" "$*"; }
warn() { printf '%s⚠%s %s\n' "$_y" "$_z" "$*" >&2; }
die()  { printf '%s✗%s %s\n' "$_r" "$_z" "$*" >&2; exit 1; }
step() { printf '\n%s%s▸%s %s%s%s\n' "$_b" "$_g" "$_z" "$_b" "$*" "$_z"; }

# ── prereqs ────────────────────────────────────────────────────────────────
step "Checking prerequisites"

command -v git >/dev/null 2>&1 || die "git is required but not on PATH. Install git first."

if ! command -v uv >/dev/null 2>&1; then
    warn "uv not found — bootstrapping it via the official installer"
    curl -fsSL https://astral.sh/uv/install.sh | sh
    # uv installs to ~/.local/bin (and ~/.cargo/bin on some configurations).
    # Make it findable for the rest of this script even if the user's shell
    # rc hasn't picked it up yet.
    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
    command -v uv >/dev/null 2>&1 || die "uv install completed but uv still isn't on PATH. Open a new shell and re-run."
fi

ok "git $(git --version | awk '{print $3}')"
ok "uv  $(uv --version | awk '{print $2}')"

# ── clone or update ───────────────────────────────────────────────────────
step "Fetching Nightly source"

if [ -d "$NIGHTLY_HOME/.git" ]; then
    info "$NIGHTLY_HOME is already a checkout — updating"
    git -C "$NIGHTLY_HOME" fetch --quiet --tags origin
    # `checkout` works for branches, tags, and SHAs alike.
    git -C "$NIGHTLY_HOME" checkout --quiet "$NIGHTLY_VERSION"
    # Only fast-forward if we're tracking a branch; tags/commits skip this.
    if git -C "$NIGHTLY_HOME" symbolic-ref --quiet HEAD >/dev/null 2>&1; then
        git -C "$NIGHTLY_HOME" pull --quiet --ff-only origin "$NIGHTLY_VERSION" || true
    fi
else
    mkdir -p "$(dirname "$NIGHTLY_HOME")"
    if [ -e "$NIGHTLY_HOME" ]; then
        die "$NIGHTLY_HOME exists but is not a git checkout. Move or remove it and re-run."
    fi
    git clone --quiet --branch "$NIGHTLY_VERSION" "$NIGHTLY_REPO" "$NIGHTLY_HOME"
fi

rev="$(git -C "$NIGHTLY_HOME" rev-parse --short HEAD)"
ok "source ready at $NIGHTLY_HOME ($rev)"

# ── sync dependencies ─────────────────────────────────────────────────────
step "Installing Python dependencies"
( cd "$NIGHTLY_HOME" && uv sync --all-packages --quiet )
ok "workspace synced"

# ── shim ──────────────────────────────────────────────────────────────────
step "Installing the nightly shim"
mkdir -p "$NIGHTLY_BIN"
shim="$NIGHTLY_BIN/nightly"

cat > "$shim" <<EOF
#!/usr/bin/env bash
# Auto-generated by Nightly's install.sh. Re-run install.sh to refresh.
# Source: $NIGHTLY_HOME
exec uv run --project "$NIGHTLY_HOME" --quiet nightly "\$@"
EOF
chmod +x "$shim"
ok "wrote $shim"

# ── PATH hint ─────────────────────────────────────────────────────────────
case ":$PATH:" in
    *":$NIGHTLY_BIN:"*)
        ;;  # already on PATH
    *)
        warn "$NIGHTLY_BIN is not on PATH"
        echo "    Add this to your shell rc (~/.zshrc, ~/.bashrc, ~/.config/fish/config.fish):"
        echo
        echo "        export PATH=\"$NIGHTLY_BIN:\$PATH\""
        echo
        echo "    Then open a new shell or 'source' the rc file to pick it up."
        ;;
esac

# ── smoke test ────────────────────────────────────────────────────────────
step "Verifying the install"
ver_out="$("$shim" version 2>&1 || true)"
if printf '%s' "$ver_out" | grep -q '^nightly'; then
    ok "$ver_out"
else
    warn "smoke test didn't print a version string — output was:"
    printf '%s\n' "$ver_out" | sed 's/^/        /' >&2
fi

# ── next steps ────────────────────────────────────────────────────────────
cat <<EOF

${_b}${_g}Next steps:${_z}

  ${_d}# install the host skill globally, then bootstrap each repo with /nightly-init${_z}
  nightly init --scope user                       ${_d}# default host = claude${_z}
  nightly init --host codex --scope user          ${_d}# or codex / opencode / cursor / antigravity / gemini${_z}

  ${_d}# explore${_z}
  nightly --help                ${_d}# full command surface${_z}
  nightly status                ${_d}# repo state, installed hosts, current run${_z}

${_b}Source:${_z}  $NIGHTLY_HOME
${_b}Design:${_z}  $NIGHTLY_HOME/.planning/brainstorm.html
${_b}Update:${_z}  re-run $(basename "$0") (idempotent)
EOF
