"""Dashboard renderer — SQLite vault index → single-page graph UI.

Emits `<vault>/_dashboard/`:

```
_dashboard/
├── index.html        # SPA shell — boots sql.js, loads index.db, renders
├── app.js            # filter UI + cytoscape graph wiring
├── style.css         # copied from vault/assets/style.css
├── cytoscape.min.js  # vendored
├── sql-wasm.js       # vendored
└── sql-wasm-inline.js # base64-inlined wasm + locateFile override
```

The dashboard reads only SQLite — no markdown bodies, no per-node prose
pages. Filters compose into a WHERE clause and re-query in the browser.
Cytoscape renders nodes sized by in-degree (heavy-feedback PRs grow).

Per RFC 003 Fork 06, the wasm is base64-inlined so the dashboard opens
from `file://` with no server lifecycle. Cold load is ~1.2MB; cached
forever after first open.
"""

from __future__ import annotations

import base64
import shutil
from dataclasses import dataclass
from pathlib import Path

from .index import INDEX_DB_NAME

__all__ = ["DashboardResult", "render"]


_ASSETS_SRC = Path(__file__).parent / "assets"


@dataclass(frozen=True)
class DashboardResult:
    dashboard_root: Path
    index_path: Path
    db_copy: Path


def render(vault_root: Path) -> DashboardResult:
    """Render the dashboard under `<vault_root>/_dashboard/`.

    Requires `_index.db` to exist; raises `FileNotFoundError` otherwise.
    """
    db_path = vault_root / INDEX_DB_NAME
    if not db_path.exists():
        msg = f"index DB not found; run index.rebuild() first: {db_path}"
        raise FileNotFoundError(msg)

    dashboard_root = vault_root / "_dashboard"
    dashboard_root.mkdir(parents=True, exist_ok=True)

    # Copy the DB so the dashboard has a stable artifact under _dashboard/
    db_copy = dashboard_root / "vault.db"
    shutil.copy2(db_path, db_copy)

    # Static assets — style + cytoscape + sql.js loader
    for name in ("style.css", "cytoscape.min.js", "sql-wasm.js"):
        src = _ASSETS_SRC / name
        if src.is_file():
            shutil.copy2(src, dashboard_root / name)

    # Inline the wasm as base64 in a sibling JS module so the page opens
    # under `file://` (browsers reject `fetch()` of a sibling .wasm there).
    wasm_path = _ASSETS_SRC / "sql-wasm.wasm"
    if wasm_path.is_file():
        wasm_b64 = base64.b64encode(wasm_path.read_bytes()).decode("ascii")
        inline = (
            "// Generated by render_dashboard.py — base64-inlined sql.js wasm.\n"
            "// Configures sql.js's `locateFile` to return a data: URI so the\n"
            "// dashboard works without a server (file:// opens fine).\n"
            f'window.__VAULT_SQL_WASM_DATA__ = "data:application/wasm;base64,{wasm_b64}";\n'
        )
        (dashboard_root / "sql-wasm-inline.js").write_text(inline, encoding="utf-8")

    # Dashboard app — small SPA with no framework
    (dashboard_root / "app.js").write_text(_APP_JS, encoding="utf-8")

    # HTML shell
    index_path = dashboard_root / "index.html"
    index_path.write_text(_INDEX_HTML, encoding="utf-8")

    return DashboardResult(
        dashboard_root=dashboard_root,
        index_path=index_path,
        db_copy=db_copy,
    )


# ── templates ─────────────────────────────────────────────────────────────


_INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nightly — vault dashboard</title>
<link rel="stylesheet" href="style.css">
<style>
  .dashboard { max-width: 1400px; margin: 0 auto; padding: 3rem 24px 4rem; }
  .top { display: flex; align-items: baseline; justify-content: space-between; flex-wrap: wrap; gap: 1rem; margin-bottom: 2rem; }
  .top h1 { font-size: clamp(1.8rem, 3vw, 2.6rem); margin: 0; }
  .top .totals { font: .82rem/1.4 ui-monospace,monospace; color: var(--muted); }
  .top .totals b { color: var(--paper); }
  .layout { display: grid; grid-template-columns: 280px 1fr; gap: 1.4rem; align-items: start; }
  @media (max-width: 900px) { .layout { grid-template-columns: 1fr; } }
  .sidebar { background: var(--ink-2); border: 1px solid var(--line); border-radius: var(--r-lg); padding: 1.2rem 1.2rem 1.4rem; position: sticky; top: 1rem; max-height: calc(100vh - 2rem); overflow-y: auto; }
  .sidebar h3 { font: 600 .68rem/1 ui-monospace,monospace; text-transform: uppercase; letter-spacing: .16em; color: var(--copper); margin: 1.4rem 0 .6rem; }
  .sidebar h3:first-child { margin-top: 0; }
  .filter-group { display: flex; flex-direction: column; gap: .4rem; }
  .filter-chip { display: flex; align-items: center; gap: .5rem; cursor: pointer; font: .82rem/1.4 ui-monospace,monospace; color: var(--paper-dim); padding: .3rem .5rem; border-radius: var(--r-sm); }
  .filter-chip:hover { background: var(--ink-3); }
  .filter-chip input { margin: 0; accent-color: var(--copper); }
  .filter-chip .count { margin-left: auto; color: var(--muted); font-size: .7rem; }
  .filter-chip.active { color: var(--paper); }
  .panel { background: var(--ink-2); border: 1px solid var(--line); border-radius: var(--r-lg); padding: 0; overflow: hidden; }
  .panel-head { display: flex; align-items: baseline; justify-content: space-between; padding: 1rem 1.4rem; border-bottom: 1px solid var(--line); }
  .panel-head h2 { margin: 0; font-size: .82rem; }
  .panel-head .panel-meta { font: .78rem/1.4 ui-monospace,monospace; color: var(--muted); }
  #graph { width: 100%; height: 640px; background: var(--ink); }
  .results { padding: 0; }
  table.nodes { width: 100%; border-collapse: collapse; font: .85rem/1.4 ui-monospace,monospace; }
  table.nodes th, table.nodes td { padding: .55rem .8rem; text-align: left; border-bottom: 1px solid var(--line); }
  table.nodes th { font: 600 .65rem/1 ui-monospace,monospace; text-transform: uppercase; letter-spacing: .14em; color: var(--copper); position: sticky; top: 0; background: var(--ink-2); z-index: 1; }
  table.nodes tr:hover td { background: var(--ink-3); }
  table.nodes a { color: var(--paper); }
  .date-range { display: flex; gap: .4rem; align-items: center; }
  .date-range input { background: var(--ink-3); border: 1px solid var(--line); color: var(--paper); padding: .3rem .5rem; border-radius: var(--r-sm); font: .8rem/1.4 ui-monospace,monospace; width: 100%; }
  .status-banner { padding: .8rem 1.4rem; background: var(--ink-3); color: var(--muted); font: .82rem/1.4 ui-monospace,monospace; display: none; }
  .status-banner.show { display: block; }
  .status-banner.error { background: rgba(224,122,120,.1); color: var(--rose); }
</style>
</head>
<body>
<main class="dashboard">
  <div class="top">
    <div>
      <div class="eyebrow"><span class="dot"></span>vault · dashboard</div>
      <h1>Knowledge graph</h1>
    </div>
    <div class="totals">
      <b>Nodes</b>&nbsp; <span id="total-nodes">…</span>
      &nbsp;·&nbsp; <b>Edges</b>&nbsp; <span id="total-edges">…</span>
      &nbsp;·&nbsp; <b>Last built</b>&nbsp; <span id="last-built">—</span>
    </div>
  </div>

  <div class="status-banner" id="status-banner"></div>

  <div class="layout">
    <aside class="sidebar">
      <h3>Kinds</h3>
      <div class="filter-group" id="kind-filters"></div>

      <h3>Status</h3>
      <div class="filter-group" id="status-filters"></div>

      <h3>Date range</h3>
      <div class="date-range">
        <input type="date" id="date-from" />
        <input type="date" id="date-to" />
      </div>

      <h3>Limit</h3>
      <div class="filter-group">
        <label class="filter-chip"><input type="radio" name="limit" value="7"   checked />last 7 days</label>
        <label class="filter-chip"><input type="radio" name="limit" value="30"           />last 30 days</label>
        <label class="filter-chip"><input type="radio" name="limit" value="all"          />all time</label>
      </div>
    </aside>

    <div>
      <section class="panel">
        <div class="panel-head">
          <h2>Graph</h2>
          <div class="panel-meta"><span id="graph-meta">—</span></div>
        </div>
        <div id="graph"></div>
      </section>

      <section class="panel" style="margin-top: 1.4rem;">
        <div class="panel-head">
          <h2>Matching nodes</h2>
          <div class="panel-meta"><span id="results-meta">—</span></div>
        </div>
        <div class="results">
          <table class="nodes" id="results-table">
            <thead>
              <tr><th>kind</th><th>title</th><th>status</th><th>created</th></tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </section>
    </div>
  </div>
</main>

<script src="cytoscape.min.js"></script>
<script src="sql-wasm-inline.js"></script>
<script src="sql-wasm.js"></script>
<script src="app.js"></script>
</body>
</html>
"""


_APP_JS = """// Vault dashboard — boots sql.js, opens vault.db, wires filter UI + cytoscape.

(async function() {
  const banner = document.getElementById("status-banner");
  function statusError(msg) { banner.textContent = msg; banner.classList.add("show", "error"); }
  function statusInfo(msg)  { banner.textContent = msg; banner.classList.add("show"); banner.classList.remove("error"); }
  function statusClear()    { banner.classList.remove("show"); }

  if (typeof initSqlJs !== "function") {
    statusError("sql.js failed to load — check that sql-wasm.js shipped with the dashboard.");
    return;
  }

  statusInfo("Loading dashboard…");

  let SQL;
  try {
    SQL = await initSqlJs({
      locateFile: () => window.__VAULT_SQL_WASM_DATA__,
    });
  } catch (err) {
    statusError("Could not initialize sql.js: " + err.message);
    return;
  }

  let db;
  try {
    const res = await fetch("vault.db");
    if (!res.ok) throw new Error("HTTP " + res.status);
    const buf = await res.arrayBuffer();
    db = new SQL.Database(new Uint8Array(buf));
  } catch (err) {
    statusError(
      "Could not load vault.db: " + err.message +
      ". If you opened this from file://, the browser may block local DB fetches. " +
      "Run `nightly vault serve` and reopen via http://localhost:8123 instead."
    );
    return;
  }

  statusClear();

  // ── load summary ────────────────────────────────────────────────────────
  function scalar(sql, params) {
    const r = db.exec(sql, params)[0];
    if (!r) return null;
    return r.values[0][0];
  }

  document.getElementById("total-nodes").textContent =
    scalar("SELECT COUNT(*) FROM nodes WHERE kind != 'unknown'") || 0;
  document.getElementById("total-edges").textContent = scalar("SELECT COUNT(*) FROM edges") || 0;
  document.getElementById("last-built").textContent =
    scalar("SELECT MAX(updated) FROM nodes") || "—";

  // ── populate filter chips ───────────────────────────────────────────────
  const KIND_ORDER = ["run", "task", "dispatch", "pr", "feedback", "lesson", "unknown"];
  const kindCounts = {};
  db.exec("SELECT kind, COUNT(*) FROM nodes GROUP BY kind")[0]?.values?.forEach(([k, c]) => {
    kindCounts[k] = c;
  });

  const kindBox = document.getElementById("kind-filters");
  KIND_ORDER.forEach(kind => {
    if (!(kind in kindCounts)) return;
    const id = `kind-${kind}`;
    const lbl = document.createElement("label");
    lbl.className = "filter-chip active";
    lbl.innerHTML = `<input type="checkbox" id="${id}" data-kind="${kind}" checked/>` +
      `<span class="chip ${kind}"><span class="dot"></span>${kind}</span>` +
      `<span class="count">${kindCounts[kind]}</span>`;
    kindBox.appendChild(lbl);
  });

  const statuses = {};
  db.exec("SELECT status, COUNT(*) FROM nodes WHERE status IS NOT NULL GROUP BY status")[0]
    ?.values?.forEach(([s, c]) => { statuses[s] = c; });
  const statusBox = document.getElementById("status-filters");
  Object.keys(statuses).sort().forEach(status => {
    const lbl = document.createElement("label");
    lbl.className = "filter-chip active";
    lbl.innerHTML = `<input type="checkbox" data-status="${status}" checked/>` +
      `<span class="pill ${status}">${status}</span>` +
      `<span class="count">${statuses[status]}</span>`;
    statusBox.appendChild(lbl);
  });

  // ── filter compilation ──────────────────────────────────────────────────
  function activeKinds() {
    return [...document.querySelectorAll("[data-kind]:checked")].map(el => el.dataset.kind);
  }
  function activeStatuses() {
    return [...document.querySelectorAll("[data-status]:checked")].map(el => el.dataset.status);
  }
  function activeLimitDays() {
    const el = document.querySelector("input[name=limit]:checked");
    return el && el.value !== "all" ? parseInt(el.value, 10) : null;
  }
  function dateBounds() {
    return {
      from: document.getElementById("date-from").value || null,
      to:   document.getElementById("date-to").value   || null,
    };
  }

  function buildWhere() {
    const conds = [];
    const params = {};
    const kinds = activeKinds();
    if (kinds.length === 0) return { sql: " WHERE 0", params };
    conds.push(`kind IN (${kinds.map((_,i) => `:k${i}`).join(",")})`);
    kinds.forEach((k, i) => { params[`:k${i}`] = k; });

    const stats = activeStatuses();
    if (stats.length > 0) {
      conds.push(`(status IN (${stats.map((_,i) => `:s${i}`).join(",")}) OR status IS NULL)`);
      stats.forEach((s, i) => { params[`:s${i}`] = s; });
    }

    const lim = activeLimitDays();
    if (lim !== null) {
      conds.push("created >= date('now', :rel)");
      params[":rel"] = `-${lim} days`;
    }
    const { from, to } = dateBounds();
    if (from) { conds.push("created >= :from"); params[":from"] = from; }
    if (to)   { conds.push("created <= :to");   params[":to"]   = to;   }

    return { sql: " WHERE " + conds.join(" AND "), params };
  }

  // ── render results table ────────────────────────────────────────────────
  function renderTable() {
    const { sql, params } = buildWhere();
    const q = `SELECT id, kind, title, status, created FROM nodes${sql} ORDER BY created DESC LIMIT 500`;
    const tbody = document.querySelector("#results-table tbody");
    tbody.innerHTML = "";
    const res = db.exec(q, params)[0];
    if (!res) {
      document.getElementById("results-meta").textContent = "0 nodes";
      return;
    }
    res.values.forEach(([id, kind, title, status, created]) => {
      const slug = id.includes("/") ? id.split("/").slice(1).join("/") : id;
      const kindDir = ({
        run: "runs", task: "tasks", dispatch: "dispatches",
        pr: "pulls", feedback: "feedback", lesson: "lessons",
      })[kind] || kind;
      const href = `../_site/${kindDir}/${slug}.html`;
      const tr = document.createElement("tr");
      tr.innerHTML =
        `<td><span class="chip ${kind}"><span class="dot"></span>${kind}</span></td>` +
        `<td><a href="${href}">${escapeHtml(title || id)}</a></td>` +
        `<td>${status ? `<span class="pill ${status}">${status}</span>` : ""}</td>` +
        `<td>${created || ""}</td>`;
      tbody.appendChild(tr);
    });
    document.getElementById("results-meta").textContent =
      `${res.values.length} node${res.values.length === 1 ? "" : "s"}`;
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;" }[c]));
  }

  // ── render graph ────────────────────────────────────────────────────────
  let cy = null;
  function renderGraph() {
    const { sql, params } = buildWhere();
    // Visible nodes
    const nodesRes = db.exec(
      `SELECT id, kind, title, status FROM nodes${sql} ORDER BY created DESC LIMIT 500`, params)[0];
    const visibleIds = new Set();
    const elements = [];
    if (nodesRes) {
      nodesRes.values.forEach(([id, kind, title, _status]) => {
        visibleIds.add(id);
        elements.push({
          data: { id, kind, label: title || id, indeg: 0 },
        });
      });
    }
    // Edges where both endpoints are visible
    if (visibleIds.size > 0) {
      const ids = [...visibleIds];
      const placeholders = ids.map((_, i) => `:e${i}`).join(",");
      const eparams = {};
      ids.forEach((id, i) => { eparams[`:e${i}`] = id; });
      const er = db.exec(
        `SELECT src_id, dst_id, edge_type FROM edges
         WHERE src_id IN (${placeholders}) AND dst_id IN (${placeholders})`,
        eparams,
      )[0];
      if (er) {
        er.values.forEach(([src, dst, et]) => {
          elements.push({ data: { source: src, target: dst, label: et } });
        });
      }
    }
    // Compute in-degree for node sizing
    const indeg = {};
    elements.forEach(el => {
      if (el.data.target) indeg[el.data.target] = (indeg[el.data.target] || 0) + 1;
    });
    elements.forEach(el => {
      if (!el.data.target) el.data.indeg = indeg[el.data.id] || 0;
    });

    document.getElementById("graph-meta").textContent =
      `${visibleIds.size} nodes · ${elements.length - visibleIds.size} edges`;

    if (cy) cy.destroy();
    cy = cytoscape({
      container: document.getElementById("graph"),
      elements,
      layout: { name: "cose", animate: false, idealEdgeLength: 110, nodeRepulsion: 9000 },
      style: [
        { selector: "node", style: {
            "background-color": "data(kindColor)",
            "label": "data(label)",
            "color": "#C9C2B4",
            "font-size": 9,
            "font-family": "ui-monospace, monospace",
            "text-margin-y": -6,
            "width":  ele => 16 + Math.sqrt(ele.data("indeg") || 0) * 6,
            "height": ele => 16 + Math.sqrt(ele.data("indeg") || 0) * 6,
        } },
        { selector: "node[kind = 'run']",      style: { "background-color": "#E8A857" } },
        { selector: "node[kind = 'task']",     style: { "background-color": "#6FD0BD" } },
        { selector: "node[kind = 'dispatch']", style: { "background-color": "#8A8676" } },
        { selector: "node[kind = 'pr']",       style: { "background-color": "#B58BD9" } },
        { selector: "node[kind = 'feedback']", style: { "background-color": "#E07A78" } },
        { selector: "node[kind = 'lesson']",   style: { "background-color": "#C9C2B4" } },
        { selector: "node[kind = 'unknown']",  style: { "background-color": "#2E3543" } },
        { selector: "edge", style: {
            "width": 1,
            "line-color": "#2E3543",
            "target-arrow-color": "#2E3543",
            "target-arrow-shape": "triangle",
            "curve-style": "bezier",
            "opacity": 0.65,
        } },
      ],
    });

    cy.on("tap", "node", evt => {
      const id = evt.target.id();
      const kind = evt.target.data("kind");
      const slug = id.includes("/") ? id.split("/").slice(1).join("/") : id;
      const kindDir = ({
        run: "runs", task: "tasks", dispatch: "dispatches",
        pr: "pulls", feedback: "feedback", lesson: "lessons",
      })[kind] || kind;
      window.open(`../_site/${kindDir}/${slug}.html`, "_blank");
    });
  }

  function rerender() {
    document.querySelectorAll(".filter-chip").forEach(el => {
      const input = el.querySelector("input");
      if (!input) return;
      el.classList.toggle("active", input.checked);
    });
    renderTable();
    renderGraph();
  }

  document.querySelectorAll("input").forEach(el =>
    el.addEventListener("change", rerender)
  );

  rerender();
})();
"""
