# Homebrew formula scaffold for ulmentflam/homebrew-tap.
#
# Deploy by copying this file to Formula/nightly.rb in the tap repo
# (https://github.com/ulmentflam/homebrew-tap). On each Nightly release,
# bump `url` to the new tag URL and `sha256` to the matching tarball's
# digest (`shasum -a 256 nightly-<version>.tar.gz`). A release-CI job
# can automate this with `brew bump-formula-pr`.
#
# Install (tagged release once one exists):
#   brew install ulmentflam/tap/nightly
#
# Install (current main, no tag required):
#   brew install --HEAD ulmentflam/tap/nightly
#
# Upgrade:
#   brew upgrade nightly
#
# Inspiration: ulmentflam/corpus-forge's packaging/distribution/corpus-forge.rb.
# Departure from that template: Nightly is a uv workspace (one core
# package + six host packages), so `virtualenv_install_with_resources`
# can't drive the install — pip-against-the-tarball misses the workspace
# siblings. We delegate to `uv sync --all-packages` instead. Same path
# `install.sh` takes.
class Nightly < Formula
  desc "Host-native coding agent that drains your backlog overnight"
  homepage "https://github.com/ulmentflam/nightly"
  url "https://github.com/ulmentflam/nightly/archive/refs/tags/v0.0.12.tar.gz"
  # Update this on each tagged release. Until v0.0.1 is tagged, use
  # `brew install --HEAD ulmentflam/tap/nightly` to install from main.
  sha256 "2de7102d660cc37019244c0441e70d22a7622a868f37cb12d941fb6395851263"
  license "MIT"
  head "https://github.com/ulmentflam/nightly.git", branch: "main"

  depends_on "python@3.12"
  depends_on "uv"
  depends_on "git"

  def install
    # Move the unpacked source into libexec, then materialize the venv
    # there. We can't use `virtualenv_install_with_resources` because
    # Nightly is a uv workspace (1 core + 6 host packages); pip from
    # the tarball can only see the meta-package and misses the host
    # siblings. uv handles the workspace natively, so the formula's
    # install path mirrors `install.sh`'s.
    libexec.install Dir["*"], Dir[".[!.]*"]
    cd libexec do
      system "uv", "sync", "--all-packages", "--frozen"
    end

    # Shim into bin/. Same shape as install.sh writes to
    # ~/.local/bin/nightly — `uv run --project <src> nightly ...`.
    # `--frozen --no-sync`: the venv was fully materialized above, and the
    # installed tree under libexec is read-only, so uv must NOT try to
    # re-resolve (which writes uv.lock) or re-sync (which writes .venv) at
    # runtime — either fails with "Operation not permitted" in the Cellar.
    (bin/"nightly").write <<~SHIM
      #!/bin/bash
      # Auto-generated by the Homebrew formula. Mirror of install.sh's shim.
      # Source: #{libexec}
      exec uv run --project "#{libexec}" --frozen --no-sync --quiet nightly "$@"
    SHIM
    chmod 0755, bin/"nightly"
  end

  def caveats
    <<~EOS
      Nightly is installed at #{opt_bin}/nightly.

      One-time setup — install the host skill globally:

        nightly init --scope user

      Valid hosts: claude (default), codex, opencode, cursor, antigravity, gemini.
      Pass --host <name> to target a non-default host.

      Then in any repo, type `/nightly-init` inside your host to
      bootstrap that repo's .nightly/ scaffold. Or run `nightly init`
      directly in a repo for one-shot project-scope setup.

      Docs:  https://github.com/ulmentflam/nightly#install
      Issue: https://github.com/ulmentflam/nightly/issues
    EOS
  end

  test do
    # Smoke: `nightly version` prints something starting with "nightly".
    assert_match "nightly", shell_output("#{bin}/nightly version")
    # Smoke: `--help` exits 0 and lists at least one known command.
    help = shell_output("#{bin}/nightly --help")
    assert_match "init", help
    assert_match "next", help
  end
end
